export type ElementCategory =
    | 'noble-gas'
    | 'alkali-metal'
    | 'alkaline-earth'
    | 'transition-metal'
    | 'post-transition-metal'
    | 'metalloid'
    | 'nonmetal'
    | 'lanthanide'
    | 'actinide'
    | 'alkaline-earth-metal'
    | 'unknown';

export interface Element {
    atomicNumber: number;
    symbol: string;
    name: string;
    atomicWeight: number;
    category: ElementCategory;
    electronConfiguration: string;
    electronegativity?: number | null;
    density?: number;
    meltingPoint?: number;
    boilingPoint?: number;
    discoveredBy?: string;
    discoveryYear?: number | null;
    description: string;
    commonUses?: string[];
}

// Periodic table data - includes all elements
export const elementsData: Element[] = [
    {
        atomicNumber: 1,
        symbol: 'H',
        name: 'Hydrogen',
        atomicWeight: 1.008,
        category: 'nonmetal',
        electronConfiguration: '1s¹',
        electronegativity: 2.2,
        density: 0.0000899,
        meltingPoint: -259.16,
        boilingPoint: -252.879,
        discoveredBy: 'Henry Cavendish',
        discoveryYear: 1766,
        description: 'Hydrogen is the lightest and most abundant chemical element in the universe, constituting approximately 75% of all normal matter.',
        commonUses: ['Fuel', 'Ammonia production', 'Oil refining', 'Rocket fuel']
    },
    {
        atomicNumber: 2,
        symbol: 'He',
        name: 'Helium',
        atomicWeight: 4.0026,
        category: 'noble-gas',
        electronConfiguration: '1s²',
        electronegativity: null,
        density: 0.0001785,
        meltingPoint: -272.2,
        boilingPoint: -268.93,
        discoveredBy: 'Pierre Janssen, Norman Lockyer',
        discoveryYear: 1868,
        description: 'Helium is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table.',
        commonUses: ['Balloons', 'Cooling MRI machines', 'Diving mixture', 'Leak detection']
    },
    {
        atomicNumber: 3,
        symbol: 'Li',
        name: 'Lithium',
        atomicWeight: 6.94,
        category: 'alkali-metal',
        electronConfiguration: '1s² 2s¹',
        electronegativity: 0.98,
        density: 0.534,
        meltingPoint: 180.50,
        boilingPoint: 1342,
        discoveredBy: 'Johan August Arfwedson',
        discoveryYear: 1817,
        description: 'Lithium is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element.',
        commonUses: ['Batteries', 'Medication', 'Aerospace alloys', 'Nuclear fusion']
    },
    {
        atomicNumber: 4,
        symbol: 'Be',
        name: 'Beryllium',
        atomicWeight: 9.0122,
        category: 'alkaline-earth-metal',
        electronConfiguration: '1s² 2s²',
        electronegativity: 1.57,
        density: 1.85,
        meltingPoint: 1287,
        boilingPoint: 2470,
        discoveredBy: 'Louis Nicolas Vauquelin',
        discoveryYear: 1798,
        description: 'Beryllium is a hard, grayish metal naturally found in mineral rocks, coal, soil, and volcanic dust.',
        commonUses: ['Aerospace components', 'Nuclear reactors', 'X-ray windows', 'Mirrors']
    },
    {
        atomicNumber: 5,
        symbol: 'B',
        name: 'Boron',
        atomicWeight: 10.81,
        category: 'metalloid',
        electronConfiguration: '1s² 2s² 2p¹',
        electronegativity: 2.04,
        density: 2.34,
        meltingPoint: 2076,
        boilingPoint: 3927,
        discoveredBy: 'Joseph Louis Gay-Lussac, Louis Jacques Thénard',
        discoveryYear: 1808,
        description: 'Boron is a metalloid found in small amounts in the Earth’s crust, used in various industrial applications.',
        commonUses: ['Glass manufacturing', 'Fertilizers', 'Detergents', 'Semiconductors']
    },
    {
        atomicNumber: 6,
        symbol: 'C',
        name: 'Carbon',
        atomicWeight: 12.011,
        category: 'nonmetal',
        electronConfiguration: '1s² 2s² 2p²',
        electronegativity: 2.55,
        density: 2.267,
        meltingPoint: 3550,
        boilingPoint: 4027,
        discoveredBy: 'Known since antiquity',
        discoveryYear: null,
        description: 'Carbon is a nonmetal that has been known since ancient times. Carbon is present in all known life forms and is the 4th most abundant element in the universe by mass.',
        commonUses: ['Steel making', 'Construction', 'Fuel', 'Nanotechnology']
    },
    {
        atomicNumber: 7,
        symbol: 'N',
        name: 'Nitrogen',
        atomicWeight: 14.007,
        category: 'nonmetal',
        electronConfiguration: '1s² 2s² 2p³',
        electronegativity: 3.04,
        density: 0.0012506,
        meltingPoint: -195.8,
        boilingPoint: -195.429,
        discoveredBy: 'Daniel Rutherford',
        discoveryYear: 1772,
        description: 'Nitrogen is a colorless, odorless gas that makes up 78% of Earth’s atmosphere.',
        commonUses: ['Fertilizers', 'Food preservation', 'Explosives', 'Cryogenics']
    },
    {
        atomicNumber: 8,
        symbol: 'O',
        name: 'Oxygen',
        atomicWeight: 15.999,
        category: 'nonmetal',
        electronConfiguration: '1s² 2s² 2p⁴',
        electronegativity: 3.44,
        density: 0.001429,
        meltingPoint: -218.79,
        boilingPoint: -182.962,
        discoveredBy: 'Carl Wilhelm Scheele, Joseph Priestley',
        discoveryYear: 1774,
        description: 'Oxygen is a highly reactive nonmetal and oxidizing agent that readily forms oxides with most elements.',
        commonUses: ['Medical treatment', 'Steel making', 'Rocket propellant', 'Life support']
    },
    {
        atomicNumber: 9,
        symbol: 'F',
        name: 'Fluorine',
        atomicWeight: 18.998,
        category: 'nonmetal',
        electronConfiguration: '1s² 2s² 2p⁵',
        electronegativity: 3.98,
        density: 0.001696,
        meltingPoint: -219.67,
        boilingPoint: -188.11,
        discoveredBy: 'André-Marie Ampère, Henri Moissan',
        discoveryYear: 1886,
        description: 'Fluorine is the most reactive and electronegative of all elements, a pale yellow gas.',
        commonUses: ['Toothpaste', 'Refrigerants', 'Pharmaceuticals', 'Teflon production']
    },
    {
        atomicNumber: 10,
        symbol: 'Ne',
        name: 'Neon',
        atomicWeight: 20.180,
        category: 'noble-gas',
        electronConfiguration: '1s² 2s² 2p⁶',
        electronegativity: null,
        density: 0.0008999,
        meltingPoint: -248.59,
        boilingPoint: -246.046,
        discoveredBy: 'William Ramsay, Morris Travers',
        discoveryYear: 1898,
        description: 'Neon is a colorless, odorless noble gas that glows reddish-orange in a vacuum discharge tube.',
        commonUses: ['Lighting', 'Signs', 'Cryogenics', 'Lasers']
    },
    {
        atomicNumber: 11,
        symbol: 'Na',
        name: 'Sodium',
        atomicWeight: 22.990,
        category: 'alkali-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s¹',
        electronegativity: 0.93,
        density: 0.968,
        meltingPoint: 97.794,
        boilingPoint: 882.940,
        discoveredBy: 'Humphry Davy',
        discoveryYear: 1807,
        description: 'Sodium is a soft, silvery-white, highly reactive alkali metal.',
        commonUses: ['Table salt (NaCl)', 'Street lights', 'Chemical manufacturing', 'Nuclear reactors']
    },
    {
        atomicNumber: 12,
        symbol: 'Mg',
        name: 'Magnesium',
        atomicWeight: 24.305,
        category: 'alkaline-earth-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s²',
        electronegativity: 1.31,
        density: 1.738,
        meltingPoint: 650,
        boilingPoint: 1090,
        discoveredBy: 'Joseph Black',
        discoveryYear: 1755,
        description: 'Magnesium is a shiny gray solid, the eighth most abundant element in the Earth’s crust.',
        commonUses: ['Alloys', 'Flares', 'Fireworks', 'Medicine']
    },
    {
        atomicNumber: 13,
        symbol: 'Al',
        name: 'Aluminum',
        atomicWeight: 26.982,
        category: 'post-transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p¹',
        electronegativity: 1.61,
        density: 2.70,
        meltingPoint: 660.32,
        boilingPoint: 2470,
        discoveredBy: 'Hans Christian Ørsted',
        discoveryYear: 1825,
        description: 'Aluminum is a lightweight, durable, and corrosion-resistant metal.',
        commonUses: ['Packaging', 'Construction', 'Transportation', 'Electrical wiring']
    },
    {
        atomicNumber: 14,
        symbol: 'Si',
        name: 'Silicon',
        atomicWeight: 28.085,
        category: 'metalloid',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p²',
        electronegativity: 1.90,
        density: 2.329,
        meltingPoint: 1414,
        boilingPoint: 3265,
        discoveredBy: 'Jöns Jacob Berzelius',
        discoveryYear: 1823,
        description: 'Silicon is a hard, brittle crystalline solid with a blue-grey metallic luster.',
        commonUses: ['Semiconductors', 'Solar panels', 'Glass', 'Ceramics']
    },
    {
        atomicNumber: 15,
        symbol: 'P',
        name: 'Phosphorus',
        atomicWeight: 30.974,
        category: 'nonmetal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p³',
        electronegativity: 2.19,
        density: 1.823,
        meltingPoint: 44.15,
        boilingPoint: 280.5,
        discoveredBy: 'Hennig Brand',
        discoveryYear: 1669,
        description: 'Phosphorus is a highly reactive nonmetal that exists in several allotropes.',
        commonUses: ['Fertilizers', 'Matches', 'Detergents', 'Pesticides']
    },
    {
        atomicNumber: 16,
        symbol: 'S',
        name: 'Sulfur',
        atomicWeight: 32.06,
        category: 'nonmetal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁴',
        electronegativity: 2.58,
        density: 2.07,
        meltingPoint: 115.21,
        boilingPoint: 444.6,
        discoveredBy: 'Known since antiquity',
        discoveryYear: null,
        description: 'Sulfur is a bright yellow, crystalline nonmetal abundant in nature.',
        commonUses: ['Fertilizers', 'Sulfuric acid', 'Vulcanization', 'Pharmaceuticals']
    },
    {
        atomicNumber: 17,
        symbol: 'Cl',
        name: 'Chlorine',
        atomicWeight: 35.45,
        category: 'nonmetal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁵',
        electronegativity: 3.16,
        density: 0.003214,
        meltingPoint: -101.5,
        boilingPoint: -34.04,
        discoveredBy: 'Carl Wilhelm Scheele',
        discoveryYear: 1774,
        description: 'Chlorine is a yellow-green gas, an extremely reactive element and strong oxidizing agent.',
        commonUses: ['Water disinfection', 'Bleaches', 'PVC production', 'Chemical manufacturing']
    },
    {
        atomicNumber: 18,
        symbol: 'Ar',
        name: 'Argon',
        atomicWeight: 39.948,
        category: 'noble-gas',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶',
        electronegativity: null,
        density: 0.001784,
        meltingPoint: -189.34,
        boilingPoint: -185.848,
        discoveredBy: 'Lord Rayleigh, William Ramsay',
        discoveryYear: 1894,
        description: 'Argon is a colorless, odorless noble gas, the third most abundant gas in the Earth’s atmosphere.',
        commonUses: ['Welding', 'Lighting', 'Gas chromatography', 'Insulation']
    },
    {
        atomicNumber: 19,
        symbol: 'K',
        name: 'Potassium',
        atomicWeight: 39.098,
        category: 'alkali-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹',
        electronegativity: 0.82,
        density: 0.862,
        meltingPoint: 63.5,
        boilingPoint: 759,
        discoveredBy: 'Humphry Davy',
        discoveryYear: 1807,
        description: 'Potassium is a soft, silvery-white alkali metal that reacts violently with water.',
        commonUses: ['Fertilizers', 'Soap production', 'Glass', 'Batteries']
    },
    {
        atomicNumber: 20,
        symbol: 'Ca',
        name: 'Calcium',
        atomicWeight: 40.078,
        category: 'alkaline-earth-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s²',
        electronegativity: 1.00,
        density: 1.55,
        meltingPoint: 842,
        boilingPoint: 1484,
        discoveredBy: 'Humphry Davy',
        discoveryYear: 1808,
        description: 'Calcium is a soft gray alkaline earth metal, the fifth most abundant element in the Earth’s crust.',
        commonUses: ['Construction', 'Cement', 'Dietary supplements', 'Metallurgy']
    },
    {
        atomicNumber: 21,
        symbol: 'Sc',
        name: 'Scandium',
        atomicWeight: 44.956,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹',
        electronegativity: 1.36,
        density: 2.985,
        meltingPoint: 1541,
        boilingPoint: 2836,
        discoveredBy: 'Lars Fredrik Nilson',
        discoveryYear: 1879,
        description: 'Scandium is a silvery-white transition metal, often classified as a rare-earth element.',
        commonUses: ['Aerospace alloys', 'Lighting', 'Sports equipment', 'Research']
    },
    {
        atomicNumber: 22,
        symbol: 'Ti',
        name: 'Titanium',
        atomicWeight: 47.867,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d²',
        electronegativity: 1.54,
        density: 4.506,
        meltingPoint: 1668,
        boilingPoint: 3287,
        discoveredBy: 'William Gregor',
        discoveryYear: 1791,
        description: 'Titanium is a strong, lustrous, corrosion-resistant transition metal.',
        commonUses: ['Aerospace', 'Medical implants', 'Jewelry', 'Pigments']
    },
    {
        atomicNumber: 23,
        symbol: 'V',
        name: 'Vanadium',
        atomicWeight: 50.942,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d³',
        electronegativity: 1.63,
        density: 6.11,
        meltingPoint: 1910,
        boilingPoint: 3407,
        discoveredBy: 'Andrés Manuel del Río',
        discoveryYear: 1801,
        description: 'Vanadium is a hard, silvery-gray, ductile, and malleable transition metal.',
        commonUses: ['Steel alloys', 'Catalysts', 'Batteries', 'Aerospace']
    },
    {
        atomicNumber: 24,
        symbol: 'Cr',
        name: 'Chromium',
        atomicWeight: 51.996,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 심¹ 3d⁵',
        electronegativity: 1.66,
        density: 7.19,
        meltingPoint: 1907,
        boilingPoint: 2671,
        discoveredBy: 'Louis Nicolas Vauquelin',
        discoveryYear: 1797,
        description: 'Chromium is a steely-gray, lustrous, hard, and brittle transition metal.',
        commonUses: ['Stainless steel', 'Plating', 'Pigments', 'Catalysts']
    },
    {
        atomicNumber: 25,
        symbol: 'Mn',
        name: 'Manganese',
        atomicWeight: 54.938,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁵',
        electronegativity: 1.55,
        density: 7.21,
        meltingPoint: 1246,
        boilingPoint: 2061,
        discoveredBy: 'Johan Gottlieb Gahn',
        discoveryYear: 1774,
        description: 'Manganese is a silvery-gray metal that resembles iron, hard and brittle.',
        commonUses: ['Steel production', 'Batteries', 'Fertilizers', 'Ceramics']
    },
    {
        atomicNumber: 26,
        symbol: 'Fe',
        name: 'Iron',
        atomicWeight: 55.845,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁶',
        electronegativity: 1.83,
        density: 7.874,
        meltingPoint: 1538,
        boilingPoint: 2862,
        discoveredBy: 'Known since ancient times',
        discoveryYear: null,
        description: 'Iron is the most common element on Earth by mass, forming much of Earth’s core.',
        commonUses: ['Steel production', 'Construction', 'Automotive industry', 'Tools']
    },
    {
        atomicNumber: 27,
        symbol: 'Co',
        name: 'Cobalt',
        atomicWeight: 58.933,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁷',
        electronegativity: 1.88,
        density: 8.90,
        meltingPoint: 1495,
        boilingPoint: 2927,
        discoveredBy: 'Georg Brandt',
        discoveryYear: 1735,
        description: 'Cobalt is a hard, lustrous, silver-gray transition metal.',
        commonUses: ['Batteries', 'Alloys', 'Pigments', 'Medical imaging']
    },
    {
        atomicNumber: 28,
        symbol: 'Ni',
        name: 'Nickel',
        atomicWeight: 58.693,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁸',
        electronegativity: 1.91,
        density: 8.908,
        meltingPoint: 1455,
        boilingPoint: 2913,
        discoveredBy: 'Axel Fredrik Cronstedt',
        discoveryYear: 1751,
        description: 'Nickel is a silvery-white lustrous metal with a slight golden tinge.',
        commonUses: ['Stainless steel', 'Coins', 'Batteries', 'Plating']
    },
    {
        atomicNumber: 29,
        symbol: 'Cu',
        name: 'Copper',
        atomicWeight: 63.546,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹ 3d¹⁰',
        electronegativity: 1.90,
        density: 8.96,
        meltingPoint: 1084.62,
        boilingPoint: 2560,
        discoveredBy: 'Known since antiquity',
        discoveryYear: null,
        description: 'Copper is a soft, malleable, ductile metal with high thermal and electrical conductivity.',
        commonUses: ['Electrical wiring', 'Plumbing', 'Cookware', 'Electronics']
    },
    {
        atomicNumber: 30,
        symbol: 'Zn',
        name: 'Zinc',
        atomicWeight: 65.38,
        category: 'post-transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰',
        electronegativity: 1.65,
        density: 7.14,
        meltingPoint: 419.53,
        boilingPoint: 907,
        discoveredBy: 'Known since antiquity',
        discoveryYear: null,
        description: 'Zinc is a bluish-white, lustrous, diamagnetic metal.',
        commonUses: ['Galvanizing', 'Batteries', 'Alloys', 'Supplements']
    },
    {
        atomicNumber: 31,
        symbol: 'Ga',
        name: 'Gallium',
        atomicWeight: 69.723,
        category: 'post-transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p¹',
        electronegativity: 1.81,
        density: 5.91,
        meltingPoint: 29.76,
        boilingPoint: 2204,
        discoveredBy: 'Lecoq de Boisbaudran',
        discoveryYear: 1875,
        description: 'Gallium is a soft, silvery metal that melts just above room temperature.',
        commonUses: ['Semiconductors', 'LEDs', 'Thermometers', 'Alloys']
    },
    {
        atomicNumber: 32,
        symbol: 'Ge',
        name: 'Germanium',
        atomicWeight: 72.630,
        category: 'metalloid',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p²',
        electronegativity: 2.01,
        density: 5.323,
        meltingPoint: 938.25,
        boilingPoint: 2833,
        discoveredBy: 'Clemens Winkler',
        discoveryYear: 1886,
        description: 'Germanium is a lustrous, hard, grayish-white metalloid.',
        commonUses: ['Semiconductors', 'Optics', 'Catalysts', 'Infrared detectors']
    },
    {
        atomicNumber: 33,
        symbol: 'As',
        name: 'Arsenic',
        atomicWeight: 74.922,
        category: 'metalloid',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p³',
        electronegativity: 2.18,
        density: 5.727,
        meltingPoint: 817,
        boilingPoint: 614,
        discoveredBy: 'Known since antiquity',
        discoveryYear: null,
        description: 'Arsenic is a metalloid with a metallic gray appearance, known for its toxicity.',
        commonUses: ['Pesticides', 'Semiconductors', 'Wood preservatives', 'Alloys']
    },
    {
        atomicNumber: 34,
        symbol: 'Se',
        name: 'Selenium',
        atomicWeight: 78.971,
        category: 'nonmetal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁴',
        electronegativity: 2.55,
        density: 4.819,
        meltingPoint: 221,
        boilingPoint: 685,
        discoveredBy: 'Jöns Jacob Berzelius',
        discoveryYear: 1817,
        description: 'Selenium is a nonmetal with properties intermediate between sulfur and tellurium.',
        commonUses: ['Photocells', 'Glass production', 'Supplements', 'Solar cells']
    },
    {
        atomicNumber: 35,
        symbol: 'Br',
        name: 'Bromine',
        atomicWeight: 79.904,
        category: 'nonmetal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁵',
        electronegativity: 2.96,
        density: 3.1028,
        meltingPoint: -7.2,
        boilingPoint: 58.8,
        discoveredBy: 'Antoine Jérôme Balard',
        discoveryYear: 1826,
        description: 'Bromine is a reddish-brown liquid, the only nonmetallic element that is liquid at room temperature.',
        commonUses: ['Flame retardants', 'Pesticides', 'Pharmaceuticals', 'Water treatment']
    },
    {
        atomicNumber: 36,
        symbol: 'Kr',
        name: 'Krypton',
        atomicWeight: 83.798,
        category: 'noble-gas',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶',
        electronegativity: null,
        density: 0.003749,
        meltingPoint: -157.37,
        boilingPoint: -153.415,
        discoveredBy: 'William Ramsay, Morris Travers',
        discoveryYear: 1898,
        description: 'Krypton is a colorless, odorless noble gas, used in certain types of lighting.',
        commonUses: ['Lighting', 'Lasers', 'Photographic flashes', 'Insulation']
    },
    {
        atomicNumber: 37,
        symbol: 'Rb',
        name: 'Rubidium',
        atomicWeight: 85.468,
        category: 'alkali-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹',
        electronegativity: 0.82,
        density: 1.532,
        meltingPoint: 39.31,
        boilingPoint: 688,
        discoveredBy: 'Robert Bunsen, Gustav Kirchhoff',
        discoveryYear: 1861,
        description: 'Rubidium is a soft, silvery-white alkali metal that is highly reactive.',
        commonUses: ['Atomic clocks', 'Research', 'Fireworks', 'Photocells']
    },
    {
        atomicNumber: 38,
        symbol: 'Sr',
        name: 'Strontium',
        atomicWeight: 87.62,
        category: 'alkaline-earth-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s²',
        electronegativity: 0.95,
        density: 2.64,
        meltingPoint: 777,
        boilingPoint: 1382,
        discoveredBy: 'William Cruickshank',
        discoveryYear: 1790,
        description: 'Strontium is a soft, silvery alkaline earth metal, chemically similar to calcium.',
        commonUses: ['Fireworks', 'Flares', 'Glass', 'Medical imaging']
    },
    {
        atomicNumber: 39,
        symbol: 'Y',
        name: 'Yttrium',
        atomicWeight: 88.906,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹',
        electronegativity: 1.22,
        density: 4.472,
        meltingPoint: 1526,
        boilingPoint: 3336,
        discoveredBy: 'Johan Gadolin',
        discoveryYear: 1794,
        description: 'Yttrium is a silvery-metallic transition metal, often classified as a rare-earth element.',
        commonUses: ['LEDs', 'Lasers', 'Ceramics', 'Superconductors']
    },
    {
        atomicNumber: 40,
        symbol: 'Zr',
        name: 'Zirconium',
        atomicWeight: 91.224,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d²',
        electronegativity: 1.33,
        density: 6.52,
        meltingPoint: 1855,
        boilingPoint: 4409,
        discoveredBy: 'Martin Heinrich Klaproth',
        discoveryYear: 1789,
        description: 'Zirconium is a lustrous, gray-white, strong transition metal.',
        commonUses: ['Nuclear reactors', 'Ceramics', 'Jewelry', 'Alloys']
    },
    {
        atomicNumber: 41,
        symbol: 'Nb',
        name: 'Niobium',
        atomicWeight: 92.906,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹ 4d⁴',
        electronegativity: 1.6,
        density: 8.57,
        meltingPoint: 2477,
        boilingPoint: 4744,
        discoveredBy: 'Charles Hatchett',
        discoveryYear: 1801,
        description: 'Niobium is a soft, gray, ductile transition metal.',
        commonUses: ['Steel alloys', 'Superconductors', 'Jewelry', 'Optics']
    },
    {
        atomicNumber: 42,
        symbol: 'Mo',
        name: 'Molybdenum',
        atomicWeight: 95.95,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹ 4d⁵',
        electronegativity: 2.16,
        density: 10.28,
        meltingPoint: 2623,
        boilingPoint: 4639,
        discoveredBy: 'Carl Wilhelm Scheele',
        discoveryYear: 1778,
        description: 'Molybdenum is a silvery-white, hard transition metal.',
        commonUses: ['Steel alloys', 'Catalysts', 'Lubricants', 'Pigments']
    },
    {
        atomicNumber: 43,
        symbol: 'Tc',
        name: 'Technetium',
        atomicWeight: 98,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d⁵',
        electronegativity: 1.9,
        density: 11.5,
        meltingPoint: 2157,
        boilingPoint: 4265,
        discoveredBy: 'Emilio Segrè, Carlo Perrier',
        discoveryYear: 1937,
        description: 'Technetium is a silvery-gray radioactive transition metal, the first element to be artificially produced.',
        commonUses: ['Medical imaging', 'Research', 'Corrosion protection']
    },
    {
        atomicNumber: 44,
        symbol: 'Ru',
        name: 'Ruthenium',
        atomicWeight: 101.07,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹ 4d⁷',
        electronegativity: 2.2,
        density: 12.45,
        meltingPoint: 2334,
        boilingPoint: 4150,
        discoveredBy: 'Karl Ernst Claus',
        discoveryYear: 1844,
        description: 'Ruthenium is a rare, silvery-white, hard transition metal of the platinum group.',
        commonUses: ['Catalysts', 'Electronics', 'Alloys', 'Jewelry']
    },
    {
        atomicNumber: 45,
        symbol: 'Rh',
        name: 'Rhodium',
        atomicWeight: 102.906,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹ 4d⁸',
        electronegativity: 2.28,
        density: 12.41,
        meltingPoint: 1964,
        boilingPoint: 3695,
        discoveredBy: 'William Hyde Wollaston',
        discoveryYear: 1803,
        description: 'Rhodium is a rare, silvery-white, hard, corrosion-resistant transition metal.',
        commonUses: ['Catalysts', 'Plating', 'Jewelry', 'Mirrors']
    },
    {
        atomicNumber: 46,
        symbol: 'Pd',
        name: 'Palladium',
        atomicWeight: 106.42,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 4d¹⁰',
        electronegativity: 2.20,
        density: 12.023,
        meltingPoint: 1554.9,
        boilingPoint: 2963,
        discoveredBy: 'William Hyde Wollaston',
        discoveryYear: 1803,
        description: 'Palladium is a rare, lustrous silvery-white transition metal.',
        commonUses: ['Catalysts', 'Jewelry', 'Electronics', 'Hydrogen storage']
    },
    {
        atomicNumber: 47,
        symbol: 'Ag',
        name: 'Silver',
        atomicWeight: 107.868,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹ 4d¹⁰',
        electronegativity: 1.93,
        density: 10.49,
        meltingPoint: 961.78,
        boilingPoint: 2162,
        discoveredBy: 'Known since antiquity',
        discoveryYear: null,
        description: 'Silver is a soft, white, lustrous transition metal with the highest electrical conductivity.',
        commonUses: ['Jewelry', 'Photography', 'Electronics', 'Silverware']
    },
    {
        atomicNumber: 48,
        symbol: 'Cd',
        name: 'Cadmium',
        atomicWeight: 112.414,
        category: 'post-transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰',
        electronegativity: 1.69,
        density: 8.65,
        meltingPoint: 321.07,
        boilingPoint: 767,
        discoveredBy: 'Friedrich Stromeyer',
        discoveryYear: 1817,
        description: 'Cadmium is a soft, bluish-white metal, chemically similar to zinc.',
        commonUses: ['Batteries', 'Pigments', 'Plating', 'Alloys']
    },
    {
        atomicNumber: 49,
        symbol: 'In',
        name: 'Indium',
        atomicWeight: 114.818,
        category: 'post-transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p¹',
        electronegativity: 1.78,
        density: 7.31,
        meltingPoint: 156.6,
        boilingPoint: 2072,
        discoveredBy: 'Ferdinand Reich, Hieronymous Theodor Richter',
        discoveryYear: 1863,
        description: 'Indium is a soft, silvery metal, similar to gallium.',
        commonUses: ['Semiconductors', 'Touchscreens', 'Alloys', 'Solar panels']
    },
    {
        atomicNumber: 50,
        symbol: 'Sn',
        name: 'Tin',
        atomicWeight: 118.710,
        category: 'post-transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p²',
        electronegativity: 1.96,
        density: 7.365,
        meltingPoint: 231.93,
        boilingPoint: 2602,
        discoveredBy: 'Known since antiquity',
        discoveryYear: null,
        description: 'Tin is a soft, silvery-white metal, highly ductile and malleable.',
        commonUses: ['Solder', 'Coatings', 'Alloys', 'Food packaging']
    },
    {
        atomicNumber: 51,
        symbol: 'Sb',
        name: 'Antimony',
        atomicWeight: 121.760,
        category: 'metalloid',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p³',
        electronegativity: 2.05,
        density: 6.697,
        meltingPoint: 630.63,
        boilingPoint: 1587,
        discoveredBy: 'Known since antiquity',
        discoveryYear: null,
        description: 'Antimony is a lustrous gray metalloid with a crystalline structure.',
        commonUses: ['Flame retardants', 'Alloys', 'Batteries', 'Semiconductors']
    },
    {
        atomicNumber: 52,
        symbol: 'Te',
        name: 'Tellurium',
        atomicWeight: 127.60,
        category: 'metalloid',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁴',
        electronegativity: 2.1,
        density: 6.24,
        meltingPoint: 449.51,
        boilingPoint: 988,
        discoveredBy: 'Franz-Joseph Müller von Reichenstein',
        discoveryYear: 1782,
        description: 'Tellurium is a brittle, mildly toxic, silvery-white metalloid.',
        commonUses: ['Alloys', 'Semiconductors', 'Solar cells', 'Glass']
    },
    {
        atomicNumber: 53,
        symbol: 'I',
        name: 'Iodine',
        atomicWeight: 126.904,
        category: 'nonmetal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁵',
        electronegativity: 2.5,
        density: 4.933,
        meltingPoint: 113.7,
        boilingPoint: 184.3,
        discoveredBy: 'Bernard Courtois',
        discoveryYear: 1811,
        description: 'Iodine is a lustrous, violet-black nonmetal, essential for thyroid function.',
        commonUses: ['Disinfectants', 'Supplements', 'Photography', 'Dyes']
    },
    {
        atomicNumber: 54,
        symbol: 'Xe',
        name: 'Xenon',
        atomicWeight: 131.293,
        category: 'noble-gas',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶',
        electronegativity: null,
        density: 0.005894,
        meltingPoint: -111.75,
        boilingPoint: -108.099,
        discoveredBy: 'William Ramsay, Morris Travers',
        discoveryYear: 1898,
        description: 'Xenon is a colorless, dense, odorless noble gas found in trace amounts in the atmosphere.',
        commonUses: ['Lighting', 'Lasers', 'Medical imaging', 'Propulsion']
    },
    {
        atomicNumber: 55,
        symbol: 'Cs',
        name: 'Cesium',
        atomicWeight: 132.905,
        category: 'alkali-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s¹',
        electronegativity: 0.79,
        density: 1.93,
        meltingPoint: 28.44,
        boilingPoint: 671,
        discoveredBy: 'Robert Bunsen, Gustav Kirchhoff',
        discoveryYear: 1860,
        description: 'Cesium is a soft, silvery-gold alkali metal, highly reactive with water.',
        commonUses: ['Atomic clocks', 'Drilling fluids', 'Catalysts', 'Research']
    },
    {
        atomicNumber: 56,
        symbol: 'Ba',
        name: 'Barium',
        atomicWeight: 137.327,
        category: 'alkaline-earth-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s²',
        electronegativity: 0.89,
        density: 3.51,
        meltingPoint: 727,
        boilingPoint: 1845,
        discoveredBy: 'Carl Wilhelm Scheele',
        discoveryYear: 1772,
        description: 'Barium is a soft, silvery alkaline earth metal, highly reactive.',
        commonUses: ['Medical imaging', 'Fireworks', 'Glass', 'Drilling fluids']
    },
    {
        atomicNumber: 57,
        symbol: 'La',
        name: 'Lanthanum',
        atomicWeight: 138.905,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 5d¹',
        electronegativity: 1.1,
        density: 6.162,
        meltingPoint: 920,
        boilingPoint: 3464,
        discoveredBy: 'Carl Gustaf Mosander',
        discoveryYear: 1839,
        description: 'Lanthanum is a soft, ductile, silvery-white lanthanide.',
        commonUses: ['Catalysts', 'Lighting', 'Glass', 'Batteries']
    },
    {
        atomicNumber: 58,
        symbol: 'Ce',
        name: 'Cerium',
        atomicWeight: 140.116,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹ 5d¹',
        electronegativity: 1.12,
        density: 6.770,
        meltingPoint: 798,
        boilingPoint: 3443,
        discoveredBy: 'Martin Heinrich Klaproth, Jöns Jacob Berzelius',
        discoveryYear: 1803,
        description: 'Cerium is a soft, silvery, ductile lanthanide, the most abundant rare-earth element.',
        commonUses: ['Catalysts', 'Glass polishing', 'Alloys', 'Lighting']
    },
    {
        atomicNumber: 59,
        symbol: 'Pr',
        name: 'Praseodymium',
        atomicWeight: 140.908,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f³',
        electronegativity: 1.13,
        density: 6.77,
        meltingPoint: 931,
        boilingPoint: 3520,
        discoveredBy: 'Carl Auer von Welsbach',
        discoveryYear: 1885,
        description: 'Praseodymium is a soft, silvery lanthanide, used in various alloys.',
        commonUses: ['Magnets', 'Lighting', 'Glass', 'Alloys']
    },
    {
        atomicNumber: 60,
        symbol: 'Nd',
        name: 'Neodymium',
        atomicWeight: 144.242,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f⁴',
        electronegativity: 1.14,
        density: 7.01,
        meltingPoint: 1021,
        boilingPoint: 3074,
        discoveredBy: 'Carl Auer von Welsbach',
        discoveryYear: 1885,
        description: 'Neodymium is a soft, silvery lanthanide, widely used in strong magnets.',
        commonUses: ['Magnets', 'Lasers', 'Glass', 'Electronics']
    },
    {
        atomicNumber: 61,
        symbol: 'Pm',
        name: 'Promethium',
        atomicWeight: 145,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f⁵',
        electronegativity: 1.13,
        density: 7.26,
        meltingPoint: 1042,
        boilingPoint: 3000,
        discoveredBy: 'Jacob A. Marinsky, Lawrence E. Glendenin, Charles D. Coryell',
        discoveryYear: 1945,
        description: 'Promethium is a radioactive lanthanide, used in specialized applications.',
        commonUses: ['Nuclear batteries', 'Research', 'Glow devices']
    },
    {
        atomicNumber: 62,
        symbol: 'Sm',
        name: 'Samarium',
        atomicWeight: 150.36,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f⁶',
        electronegativity: 1.17,
        density: 7.52,
        meltingPoint: 1072,
        boilingPoint: 1794,
        discoveredBy: 'Lecoq de Boisbaudran',
        discoveryYear: 1879,
        description: 'Samarium is a moderately hard, silvery lanthanide.',
        commonUses: ['Magnets', 'Cancer treatment', 'Nuclear reactors', 'Lighting']
    },
    {
        atomicNumber: 63,
        symbol: 'Eu',
        name: 'Europium',
        atomicWeight: 151.964,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f⁷',
        electronegativity: 1.2,
        density: 5.244,
        meltingPoint: 822,
        boilingPoint: 1529,
        discoveredBy: 'Eugène-Anatole Demarçay',
        discoveryYear: 1901,
        description: 'Europium is a soft, silvery lanthanide, the most reactive rare-earth element.',
        commonUses: ['Phosphors', 'Nuclear reactors', 'Anti-counterfeiting', 'Lighting']
    },
    {
        atomicNumber: 64,
        symbol: 'Gd',
        name: 'Gadolinium',
        atomicWeight: 157.25,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f⁷ 5d¹',
        electronegativity: 1.2,
        density: 7.90,
        meltingPoint: 1313,
        boilingPoint: 3273,
        discoveredBy: 'Jean Charles Galissard de Marignac',
        discoveryYear: 1880,
        description: 'Gadolinium is a silvery-white, malleable lanthanide.',
        commonUses: ['MRI contrast', 'Nuclear reactors', 'Magnets', 'Alloys']
    },
    {
        atomicNumber: 65,
        symbol: 'Tb',
        name: 'Terbium',
        atomicWeight: 158.925,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f⁹',
        electronegativity: 1.2,
        density: 8.23,
        meltingPoint: 1356,
        boilingPoint: 3230,
        discoveredBy: 'Carl Gustaf Mosander',
        discoveryYear: 1843,
        description: 'Terbium is a silvery-white, soft lanthanide.',
        commonUses: ['Phosphors', 'Magnets', 'Lasers', 'Alloys']
    },
    {
        atomicNumber: 66,
        symbol: 'Dy',
        name: 'Dysprosium',
        atomicWeight: 162.500,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁰',
        electronegativity: 1.22,
        density: 8.551,
        meltingPoint: 1412,
        boilingPoint: 2567,
        discoveredBy: 'Lecoq de Boisbaudran',
        discoveryYear: 1886,
        description: 'Dysprosium is a soft, silvery lanthanide with high magnetic strength.',
        commonUses: ['Magnets', 'Nuclear reactors', 'Lasers', 'Lighting']
    },
    {
        atomicNumber: 67,
        symbol: 'Ho',
        name: 'Holmium',
        atomicWeight: 164.930,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹¹',
        electronegativity: 1.23,
        density: 8.795,
        meltingPoint: 1474,
        boilingPoint: 2700,
        discoveredBy: 'Marc Delafontaine, Per Teodor Cleve',
        discoveryYear: 1878,
        description: 'Holmium is a soft, silvery lanthanide with strong magnetic properties.',
        commonUses: ['Magnets', 'Nuclear reactors', 'Lasers', 'Research']
    },
    {
        atomicNumber: 68,
        symbol: 'Er',
        name: 'Erbium',
        atomicWeight: 167.259,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹²',
        electronegativity: 1.24,
        density: 9.066,
        meltingPoint: 1529,
        boilingPoint: 2868,
        discoveredBy: 'Carl Gustaf Mosander',
        discoveryYear: 1843,
        description: 'Erbium is a silvery-white, soft lanthanide.',
        commonUses: ['Fiber optics', 'Lasers', 'Glass', 'Nuclear reactors']
    },
    {
        atomicNumber: 69,
        symbol: 'Tm',
        name: 'Thulium',
        atomicWeight: 168.934,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹³',
        electronegativity: 1.25,
        density: 9.321,
        meltingPoint: 1545,
        boilingPoint: 1950,
        discoveredBy: 'Per Teodor Cleve',
        discoveryYear: 1879,
        description: 'Thulium is a soft, silvery lanthanide, one of the rarest rare-earth elements.',
        commonUses: ['Medical imaging', 'Lasers', 'Magnets', 'Research']
    },
    {
        atomicNumber: 70,
        symbol: 'Yb',
        name: 'Ytterbium',
        atomicWeight: 173.045,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴',
        electronegativity: 1.1,
        density: 6.90,
        meltingPoint: 819,
        boilingPoint: 1196,
        discoveredBy: 'Jean Charles Galissard de Marignac',
        discoveryYear: 1878,
        description: 'Ytterbium is a soft, malleable, silvery lanthanide.',
        commonUses: ['Doping materials', 'Atomic clocks', 'Catalysts', 'Research']
    },
    {
        atomicNumber: 71,
        symbol: 'Lu',
        name: 'Lutetium',
        atomicWeight: 174.967,
        category: 'lanthanide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹',
        electronegativity: 1.27,
        density: 9.841,
        meltingPoint: 1663,
        boilingPoint: 3402,
        discoveredBy: 'Georges Urbain',
        discoveryYear: 1907,
        description: 'Lutetium is a silvery-white, corrosion-resistant lanthanide.',
        commonUses: ['Catalysts', 'Medical imaging', 'Research', 'Lighting']
    },
    {
        atomicNumber: 72,
        symbol: 'Hf',
        name: 'Hafnium',
        atomicWeight: 178.49,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d²',
        electronegativity: 1.3,
        density: 13.31,
        meltingPoint: 2233,
        boilingPoint: 4603,
        discoveredBy: 'Dirk Coster, George de Hevesy',
        discoveryYear: 1923,
        description: 'Hafnium is a lustrous, silvery, ductile transition metal.',
        commonUses: ['Nuclear reactors', 'Microchips', 'Alloys', 'Ceramics']
    },
    {
        atomicNumber: 73,
        symbol: 'Ta',
        name: 'Tantalum',
        atomicWeight: 180.948,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d³',
        electronegativity: 1.5,
        density: 16.69,
        meltingPoint: 3017,
        boilingPoint: 5458,
        discoveredBy: 'Anders Gustaf Ekeberg',
        discoveryYear: 1802,
        description: 'Tantalum is a rare, hard, blue-gray, lustrous transition metal.',
        commonUses: ['Capacitors', 'Surgical implants', 'Alloys', 'Chemical equipment']
    },
    {
        atomicNumber: 74,
        symbol: 'W',
        name: 'Tungsten',
        atomicWeight: 183.84,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d⁴',
        electronegativity: 2.36,
        density: 19.25,
        meltingPoint: 3422,
        boilingPoint: 5555,
        discoveredBy: 'Juan José Elhuyar, Fausto Elhuyar',
        discoveryYear: 1783,
        description: 'Tungsten is a hard, rare metal with a very high melting point.',
        commonUses: ['Filaments', 'Alloys', 'Cutting tools', 'Electrodes']
    },
    {
        atomicNumber: 75,
        symbol: 'Re',
        name: 'Rhenium',
        atomicWeight: 186.207,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d⁵',
        electronegativity: 1.9,
        density: 21.02,
        meltingPoint: 3186,
        boilingPoint: 5596,
        discoveredBy: 'Masataka Ogawa, Walter Noddack, Ida Noddack',
        discoveryYear: 1925,
        description: 'Rhenium is a silvery-gray, heavy transition metal with one of the highest melting points.',
        commonUses: ['Jet engines', 'Catalysts', 'Thermocouples', 'Alloys']
    },
    {
        atomicNumber: 76,
        symbol: 'Os',
        name: 'Osmium',
        atomicWeight: 190.23,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d⁶',
        electronegativity: 2.2,
        density: 22.59,
        meltingPoint: 3033,
        boilingPoint: 5012,
        discoveredBy: 'Smithson Tennant',
        discoveryYear: 1803,
        description: 'Osmium is a hard, brittle, bluish-white transition metal, the densest naturally occurring element.',
        commonUses: ['Alloys', 'Fountain pen tips', 'Electrical contacts', 'Catalysts']
    },
    {
        atomicNumber: 77,
        symbol: 'Ir',
        name: 'Iridium',
        atomicWeight: 192.217,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d⁷',
        electronegativity: 2.2,
        density: 22.56,
        meltingPoint: 2446,
        boilingPoint: 4428,
        discoveredBy: 'Smithson Tennant',
        discoveryYear: 1803,
        description: 'Iridium is a very hard, brittle, silvery-white transition metal, highly corrosion-resistant.',
        commonUses: ['Spark plugs', 'Crucibles', 'Alloys', 'Catalysts']
    },
    {
        atomicNumber: 78,
        symbol: 'Pt',
        name: 'Platinum',
        atomicWeight: 195.084,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s¹ 4f¹⁴ 5d⁹',
        electronegativity: 2.28,
        density: 21.45,
        meltingPoint: 1768.3,
        boilingPoint: 3825,
        discoveredBy: 'Antonio de Ulloa',
        discoveryYear: 1735,
        description: 'Platinum is a dense, malleable, ductile, precious, silver-white transition metal.',
        commonUses: ['Catalysts', 'Jewelry', 'Electrodes', 'Medical devices']
    },
    {
        atomicNumber: 79,
        symbol: 'Au',
        name: 'Gold',
        atomicWeight: 196.967,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s¹ 4f¹⁴ 5d¹⁰',
        electronegativity: 2.54,
        density: 19.32,
        meltingPoint: 1064.18,
        boilingPoint: 2856,
        discoveredBy: 'Known since antiquity',
        discoveryYear: null,
        description: 'Gold is a bright, slightly reddish-yellow, dense, soft, malleable, ductile metal.',
        commonUses: ['Jewelry', 'Currency', 'Electronics', 'Dentistry']
    },
    {
        atomicNumber: 80,
        symbol: 'Hg',
        name: 'Mercury',
        atomicWeight: 200.592,
        category: 'transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰',
        electronegativity: 2.0,
        density: 13.546,
        meltingPoint: -38.83,
        boilingPoint: 356.73,
        discoveredBy: 'Known since antiquity',
        discoveryYear: null,
        description: 'Mercury is a heavy, silvery-white metal, the only metallic element liquid at standard conditions.',
        commonUses: ['Thermometers', 'Fluorescent lamps', 'Dental amalgam', 'Batteries']
    },
    {
        atomicNumber: 81,
        symbol: 'Tl',
        name: 'Thallium',
        atomicWeight: 204.38,
        category: 'post-transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p¹',
        electronegativity: 2.04,
        density: 11.85,
        meltingPoint: 304,
        boilingPoint: 1473,
        discoveredBy: 'William Crookes',
        discoveryYear: 1861,
        description: 'Thallium is a soft, gray post-transition metal, highly toxic.',
        commonUses: ['Electronics', 'Optics', 'Pesticides', 'Research']
    },
    {
        atomicNumber: 82,
        symbol: 'Pb',
        name: 'Lead',
        atomicWeight: 207.2,
        category: 'post-transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p²',
        electronegativity: 2.33,
        density: 11.34,
        meltingPoint: 327.46,
        boilingPoint: 1749,
        discoveredBy: 'Known since antiquity',
        discoveryYear: null,
        description: 'Lead is a heavy, soft, malleable metal, denser than most common materials.',
        commonUses: ['Batteries', 'Radiation shielding', 'Bullets', 'Construction']
    },
    {
        atomicNumber: 83,
        symbol: 'Bi',
        name: 'Bismuth',
        atomicWeight: 208.980,
        category: 'post-transition-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p³',
        electronegativity: 2.02,
        density: 9.78,
        meltingPoint: 271.5,
        boilingPoint: 1564,
        discoveredBy: 'Claude François Geoffroy',
        discoveryYear: 1753,
        description: 'Bismuth is a brittle, crystalline, white metal with a slight pink tinge.',
        commonUses: ['Alloys', 'Pharmaceuticals', 'Fire sprinklers', 'Cosmetics']
    },
    {
        atomicNumber: 84,
        symbol: 'Po',
        name: 'Polonium',
        atomicWeight: 209,
        category: 'metalloid',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁴',
        electronegativity: 2.0,
        density: 9.196,
        meltingPoint: 254,
        boilingPoint: 962,
        discoveredBy: 'Marie Curie, Pierre Curie',
        discoveryYear: 1898,
        description: 'Polonium is a rare, highly radioactive metalloid.',
        commonUses: ['Nuclear batteries', 'Anti-static devices', 'Research']
    },
    {
        atomicNumber: 85,
        symbol: 'At',
        name: 'Astatine',
        atomicWeight: 210,
        category: 'metalloid',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁵',
        electronegativity: 2.2,
        density: 7,
        meltingPoint: 302,
        boilingPoint: 337,
        discoveredBy: 'Dale R. Corson, Kenneth Ross MacKenzie, Emilio Segrè',
        discoveryYear: 1940,
        description: 'Astatine is a highly radioactive metalloid, extremely rare in nature.',
        commonUses: ['Cancer treatment', 'Research']
    },
    {
        atomicNumber: 86,
        symbol: 'Rn',
        name: 'Radon',
        atomicWeight: 222,
        category: 'noble-gas',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶',
        electronegativity: null,
        density: 0.00973,
        meltingPoint: -71,
        boilingPoint: -61.7,
        discoveredBy: 'Friedrich Ernst Dorn',
        discoveryYear: 1900,
        description: 'Radon is a radioactive, colorless, odorless noble gas.',
        commonUses: ['Radiation therapy', 'Research', 'Geological studies']
    },
    {
        atomicNumber: 87,
        symbol: 'Fr',
        name: 'Francium',
        atomicWeight: 223,
        category: 'alkali-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s¹',
        electronegativity: 0.7,
        density: 2.48,
        meltingPoint: 27,
        boilingPoint: 677,
        discoveredBy: 'Marguerite Perey',
        discoveryYear: 1939,
        description: 'Francium is a highly radioactive alkali metal, extremely rare.',
        commonUses: ['Research']
    },
    {
        atomicNumber: 88,
        symbol: 'Ra',
        name: 'Radium',
        atomicWeight: 226,
        category: 'alkaline-earth-metal',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s²',
        electronegativity: 0.9,
        density: 5.5,
        meltingPoint: 700,
        boilingPoint: 1737,
        discoveredBy: 'Marie Curie, Pierre Curie',
        discoveryYear: 1898,
        description: 'Radium is a highly radioactive, silvery-white alkaline earth metal.',
        commonUses: ['Cancer treatment', 'Research', 'Luminescent paints']
    },
    {
        atomicNumber: 89,
        symbol: 'Ac',
        name: 'Actinium',
        atomicWeight: 227,
        category: 'actinide',
        electronConfiguration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 6d¹',
        electronegativity: 1.1,
        density: 10.07,
        meltingPoint: 1050,
        boilingPoint: 3200,
        discoveredBy: 'André-Louis Debierne',
        discoveryYear: 1899,
        description: 'Actinium is a soft, silvery-white, radioactive actinide.',
        commonUses: ['Cancer treatment', 'Research', 'Neutron sources']
    },
    {
        "atomicNumber": 90,
        "symbol": "Th",
        "name": "Thorium",
        "atomicWeight": 232.0377,
        "category": "actinide",
        "electronConfiguration": "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 6d²",
        "electronegativity": 1.3,
        "density": 11.72,
        "meltingPoint": 1750,
        "boilingPoint": 4788,
        "discoveredBy": "Jöns Jakob Berzelius",
        "discoveryYear": 1828,
        "description": "Thorium is a weakly radioactive metallic chemical element with a silvery appearance. It is moderately soft, malleable, and has a high melting point.",
        "commonUses": ["Nuclear fuel", "Alloying agent", "Gas mantles"]
    },
    {
        "atomicNumber": 91,
        "symbol": "Pa",
        "name": "Protactinium",
        "atomicWeight": 231.03588,
        "category": "actinide",
        "electronConfiguration": "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f² 6d¹",
        "electronegativity": 1.5,
        "density": 15.37,
        "meltingPoint": 1572,
        "boilingPoint": 4000,
        "discoveredBy": "Kasper C. Fajans and Oswald Helmuth Göhring",
        "discoveryYear": 1913,
        "description": "Protactinium is a dense, silvery-gray metal that readily reacts with oxygen, water vapor, and inorganic acids. It is highly radioactive and has few applications outside of scientific research.",
        "commonUses": ["Scientific research"]
    },
    {
        "atomicNumber": 92,
        "symbol": "U",
        "name": "Uranium",
        "atomicWeight": 238.02891,
        "category": "actinide",
        "electronConfiguration": "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f³ 6d¹",
        "electronegativity": 1.38,
        "density": 19.1,
        "meltingPoint": 1135,
        "boilingPoint": 4131,
        "discoveredBy": "Martin Heinrich Klaproth",
        "discoveryYear": 1789,
        "description": "Uranium is a heavy, silvery-white metal that is pyrophoric when finely divided. It is weakly radioactive and has the highest atomic weight of the naturally occurring elements.",
        "commonUses": ["Nuclear fuel", "Military applications", "Scientific research"]
    },
    {
        "atomicNumber": 93,
        "symbol": "Np",
        "name": "Neptunium",
        "atomicWeight": 237,
        "category": "actinide",
        "electronConfiguration": "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f⁴ 6d¹",
        "electronegativity": 1.36,
        "density": 20.45,
        "meltingPoint": 644,
        "boilingPoint": 3902,
        "discoveredBy": "Edwin McMillan and Philip H. Abelson",
        "discoveryYear": 1940,
        "description": "Neptunium is a radioactive actinide metal, the first transuranic element discovered. It is silvery and tarnishes when exposed to air, forming a dull oxide layer.",
        "commonUses": ["Scientific research", "Potential use in nuclear weapons"]
    },
    {
        "atomicNumber": 94,
        "symbol": "Pu",
        "name": "Plutonium",
        "atomicWeight": 244,
        "category": "actinide",
        "electronConfiguration": "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f⁶",
        "electronegativity": 1.28,
        "density": 19.84,
        "meltingPoint": 640,
        "boilingPoint": 3230,
        "discoveredBy": "Glenn T. Seaborg, Edwin McMillan, Joseph W. Kennedy, and Arthur Wahl",
        "discoveryYear": 1940,
        "description": "Plutonium is a radioactive, silvery-gray metal that tarnishes when exposed to air. It exhibits six allotropes and has a complex phase diagram.",
        "commonUses": ["Nuclear weapons", "Nuclear fuel", "Radioisotope thermoelectric generators"]
    },
    {
        "atomicNumber": 95,
        "symbol": "Am",
        "name": "Americium",
        "atomicWeight": 243,
        "category": "actinide",
        "electronConfiguration": "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f⁷",
        "electronegativity": 1.3,
        "density": 12,
        "meltingPoint": 1176,
        "boilingPoint": 2607,
        "discoveredBy": "Glenn T. Seaborg, Ralph A. James, and Leon O. Morgan",
        "discoveryYear": 1944,
        "description": "Americium is a synthetic radioactive metal with a silvery-white appearance. It is produced by bombarding plutonium with neutrons.",
        "commonUses": ["Smoke detectors", "Industrial gauges", "Scientific research"]
    },
    {
        "atomicNumber": 96,
        "symbol": "Cm",
        "name": "Curium",
        "atomicWeight": 247,
        "category": "actinide",
        "electronConfiguration": "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f⁷ 6d¹",
        "electronegativity": 1.3,
        "density": 13.51,
        "meltingPoint": 1340,
        "boilingPoint": 3110,
        "discoveredBy": "Glenn T. Seaborg, Ralph A. James, and Albert Ghiorso",
        "discoveryYear": 1944,
        "description": "Curium is a hard, dense, silvery metal that tarnishes slowly in air. It is highly radioactive and glows purple in the dark due to its intense radioactivity.",
        "commonUses": ["Scientific research", "Power sources for space missions"]
    },
     {
    "atomicNumber": 97,
    "symbol": "Bk",
    "name": "Berkelium",
    "atomicWeight": 247,
    "category": "actinide",
    "electronConfiguration": "[Rn] 5f9 7s2",
    "electronegativity": 1.3,
    "density": 14.78,
    "meltingPoint": 986,
    "boilingPoint": undefined,
    "discoveredBy": "Lawrence Berkeley National Laboratory",
    "discoveryYear": 1949,
    "description": "Berkelium is a synthetic radioactive metal, part of the actinide series, with limited applications due to its scarcity and radioactivity.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 98,
    "symbol": "Cf",
    "name": "Californium",
    "atomicWeight": 251,
    "category": "actinide",
    "electronConfiguration": "[Rn] 5f10 7s2",
    "electronegativity": 1.3,
    "density": 15.1,
    "meltingPoint": 900,
    "boilingPoint": undefined,
    "discoveredBy": "Lawrence Berkeley National Laboratory",
    "discoveryYear": 1950,
    "description": "Californium is a radioactive metal used in neutron sources and scientific research due to its ability to emit neutrons.",
    "commonUses": ["Neutron sources", "Scientific research"]
  },
  {
    "atomicNumber": 99,
    "symbol": "Es",
    "name": "Einsteinium",
    "atomicWeight": 252,
    "category": "actinide",
    "electronConfiguration": "[Rn] 5f11 7s2",
    "electronegativity": 1.3,
    "density": undefined,
    "meltingPoint": 860,
    "boilingPoint": undefined,
    "discoveredBy": "Lawrence Berkeley National Laboratory",
    "discoveryYear": 1952,
    "description": "Einsteinium is a synthetic, highly radioactive metal with no significant commercial applications, primarily used in scientific research.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 100,
    "symbol": "Fm",
    "name": "Fermium",
    "atomicWeight": 257,
    "category": "actinide",
    "electronConfiguration": "[Rn] 5f12 7s2",
    "electronegativity": 1.3,
    "density": undefined,
    "meltingPoint": 1527,
    "boilingPoint": undefined,
    "discoveredBy": "Lawrence Berkeley National Laboratory",
    "discoveryYear": 1952,
    "description": "Fermium is a synthetic radioactive metal, produced in minute amounts, with applications limited to scientific research.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 101,
    "symbol": "Md",
    "name": "Mendelevium",
    "atomicWeight": 258,
    "category": "actinide",
    "electronConfiguration": "[Rn] 5f13 7s2",
    "electronegativity": 1.3,
    "density": undefined,
    "meltingPoint": 827,
    "boilingPoint": undefined,
    "discoveredBy": "Lawrence Berkeley National Laboratory",
    "discoveryYear": 1955,
    "description": "Mendelevium is a synthetic radioactive metal, named after Dmitri Mendeleev, with no practical applications outside scientific research.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 102,
    "symbol": "No",
    "name": "Nobelium",
    "atomicWeight": 259,
    "category": "actinide",
    "electronConfiguration": "[Rn] 5f14 7s2",
    "electronegativity": 1.3,
    "density": undefined,
    "meltingPoint": 827,
    "boilingPoint": undefined,
    "discoveredBy": "Joint Institute for Nuclear Research",
    "discoveryYear": 1966,
    "description": "Nobelium is a synthetic radioactive metal, named after Alfred Nobel, with applications limited to scientific research.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 103,
    "symbol": "Lr",
    "name": "Lawrencium",
    "atomicWeight": 262,
    "category": "actinide",
    "electronConfiguration": "[Rn] 5f14 7s2 7p1",
    "electronegativity": 1.3,
    "density": undefined,
    "meltingPoint": 1627,
    "boilingPoint": undefined,
    "discoveredBy": "Lawrence Berkeley National Laboratory",
    "discoveryYear": 1961,
    "description": "Lawrencium is a synthetic radioactive metal, named after Ernest Lawrence, with no significant commercial applications.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 104,
    "symbol": "Rf",
    "name": "Rutherfordium",
    "atomicWeight": 267,
    "category": "transition-metal",
    "electronConfiguration": "[Rn] 5f14 6d2 7s2",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Joint Institute for Nuclear Research",
    "discoveryYear": 1964,
    "description": "Rutherfordium is a synthetic radioactive element, named after Ernest Rutherford, with applications limited to scientific research.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 105,
    "symbol": "Db",
    "name": "Dubnium",
    "atomicWeight": 268,
    "category": "transition-metal",
    "electronConfiguration": "[Rn] 5f14 6d3 7s2",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Joint Institute for Nuclear Research",
    "discoveryYear": 1967,
    "description": "Dubnium is a synthetic radioactive element, named after Dubna, Russia, with no practical applications outside scientific research.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 106,
    "symbol": "Sg",
    "name": "Seaborgium",
    "atomicWeight": 271,
    "category": "transition-metal",
    "electronConfiguration": "[Rn] 5f14 6d4 7s2",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Lawrence Berkeley National Laboratory",
    "discoveryYear": 1974,
    "description": "Seaborgium is a synthetic radioactive element, named after Glenn T. Seaborg, with applications limited to scientific research.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 107,
    "symbol": "Bh",
    "name": "Bohrium",
    "atomicWeight": 270,
    "category": "transition-metal",
    "electronConfiguration": "[Rn] 5f14 6d5 7s2",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Gesellschaft für Schwerionenforschung",
    "discoveryYear": 1981,
    "description": "Bohrium is a synthetic radioactive element, named after Niels Bohr, with no practical applications outside scientific research.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 108,
    "symbol": "Hs",
    "name": "Hassium",
    "atomicWeight": 277,
    "category": "transition-metal",
    "electronConfiguration": "[Rn] 5f14 6d6 7s2",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Gesellschaft für Schwerionenforschung",
    "discoveryYear": 1984,
    "description": "Hassium is a synthetic radioactive element, named after the German state of Hesse, with applications limited to scientific research.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 109,
    "symbol": "Mt",
    "name": "Meitnerium",
    "atomicWeight": 278,
    "category": "transition-metal",
    "electronConfiguration": "[Rn] 5f14 6d7 7s2",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Gesellschaft für Schwerionenforschung",
    "discoveryYear": 1982,
    "description": "Meitnerium is a synthetic radioactive element, named after Lise Meitner, with no practical applications outside scientific research.",
    "commonUses": ["Scientific research"]
  },
    {
    "atomicNumber": 110,
    "symbol": "Ds",
    "name": "Darmstadtium",
    "atomicWeight": 281,
    "category": "transition-metal",
    "electronConfiguration": "[Rn] 5f14 6d9 7s1",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Gesellschaft für Schwerionenforschung",
    "discoveryYear": 1994,
    "description": "Darmstadtium is a synthetic element named after the city of Darmstadt, Germany, where it was discovered. It is highly unstable and only used in research.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 111,
    "symbol": "Rg",
    "name": "Roentgenium",
    "atomicWeight": 282,
    "category": "transition-metal",
    "electronConfiguration": "[Rn] 5f14 6d10 7s1",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Gesellschaft für Schwerionenforschung",
    "discoveryYear": 1994,
    "description": "Roentgenium is a synthetic radioactive element named after Wilhelm Röntgen. It exists only in minute amounts and is used exclusively in research.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 112,
    "symbol": "Cn",
    "name": "Copernicium",
    "atomicWeight": 285,
    "category": "transition-metal",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Gesellschaft für Schwerionenforschung",
    "discoveryYear": 1996,
    "description": "Copernicium is a synthetic element named after Nicolaus Copernicus. It is extremely unstable and only produced in labs for research purposes.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 113,
    "symbol": "Nh",
    "name": "Nihonium",
    "atomicWeight": 286,
    "category": "post-transition-metal",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p1",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "RIKEN",
    "discoveryYear": 2004,
    "description": "Nihonium is a synthetic element discovered by Japanese scientists and named after Japan (Nihon). It is highly unstable and produced in trace amounts.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 114,
    "symbol": "Fl",
    "name": "Flerovium",
    "atomicWeight": 289,
    "category": "post-transition-metal",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p2",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Joint Institute for Nuclear Research",
    "discoveryYear": 1998,
    "description": "Flerovium is a synthetic element named after the Flerov Laboratory in Russia. It has a very short half-life and is used only in scientific experiments.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 115,
    "symbol": "Mc",
    "name": "Moscovium",
    "atomicWeight": 290,
    "category": "post-transition-metal",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p3",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Joint Institute for Nuclear Research",
    "discoveryYear": 2003,
    "description": "Moscovium is a synthetic element named after the Moscow region. It is highly unstable and produced in small quantities for research.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 116,
    "symbol": "Lv",
    "name": "Livermorium",
    "atomicWeight": 293,
    "category": "post-transition-metal",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p4",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Joint Institute for Nuclear Research",
    "discoveryYear": 2000,
    "description": "Livermorium is a synthetic element named after the Lawrence Livermore National Laboratory. It is highly radioactive and used in research.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 117,
    "symbol": "Ts",
    "name": "Tennessine",
    "atomicWeight": 294,
    "category": "unknown",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p5",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Joint Institute for Nuclear Research",
    "discoveryYear": 2010,
    "description": "Tennessine is a synthetic element named after Tennessee. It is extremely unstable and exists only for a fraction of a second in experiments.",
    "commonUses": ["Scientific research"]
  },
  {
    "atomicNumber": 118,
    "symbol": "Og",
    "name": "Oganesson",
    "atomicWeight": 294,
    "category": "noble-gas",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p6",
    "electronegativity": undefined,
    "density": undefined,
    "meltingPoint": undefined,
    "boilingPoint": undefined,
    "discoveredBy": "Joint Institute for Nuclear Research",
    "discoveryYear": 2002,
    "description": "Oganesson is the last known element in the periodic table. It is a noble gas but may behave differently due to relativistic effects. It is extremely short-lived.",
    "commonUses": ["Scientific research"]
  }
];